"use client";

import { useState } from "react";
import Link from "next/link";
import { useProducts } from "@/hooks/use-products";
import { useOrders } from "@/components/firebase/AdminOrdersClient";
import { dateLabel } from "@/lib/firebase-models";

function StatsGraph({ orders }: { orders: ReturnType<typeof useOrders>["orders"] }) {
  const [daysToShow, setDaysToShow] = useState(14);
  const days = Array.from({ length: daysToShow }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (daysToShow - 1 - index)); return day; });
  const points = days.map((day) => { const next = new Date(day); next.setDate(next.getDate() + 1); const daily = orders.filter((order) => { const created = order.createdAt?.toDate(); return created && created >= day && created < next; }); return { day, count: daily.length, revenue: daily.filter((order) => order.paymentStatus === "paid").reduce((sum, order) => sum + (order.totalAmount || 0), 0) }; });
  const total = points.reduce((sum, point) => sum + point.revenue, 0); const max = Math.max(...points.map((point) => point.revenue), 1); const width = 760; const height = 280; const left = 48; const right = 16; const top = 20; const bottom = 48; const chartWidth = width - left - right; const chartHeight = height - top - bottom; const x = (index: number) => left + (index / Math.max(points.length - 1, 1)) * chartWidth; const y = (value: number) => top + chartHeight - (value / max) * chartHeight; const line = points.map((point, index) => `${index ? "L" : "M"}${x(index)},${y(point.revenue)}`).join(" "); const area = `${line} L${x(points.length - 1)},${top + chartHeight} L${x(0)},${top + chartHeight} Z`; const labelStep = Math.max(1, Math.ceil(points.length / 7));
  return <section className="admin-panel stats-graph-panel"><div className="section-heading tight"><div><p className="eyebrow gold">Performance</p><h2>Revenue over the last {daysToShow} days</h2><p className="stats-graph-total">R {total.toLocaleString("en-ZA", { minimumFractionDigits: 2 })} <span>paid revenue</span></p></div><label className="stats-range-control">Range<select aria-label="Graph date range" value={daysToShow} onChange={(event) => setDaysToShow(Number(event.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label></div><div className="stats-graph-wrap"><svg aria-label={`Revenue graph for the last ${daysToShow} days`} className="stats-graph" role="img" viewBox={`0 0 ${width} ${height}`}><defs><linearGradient id="revenue-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2271b1" stopOpacity=".28" /><stop offset="1" stopColor="#2271b1" stopOpacity=".02" /></linearGradient></defs>{[0, .25, .5, .75, 1].map((fraction) => <g key={fraction}><line className="stats-graph-grid" x1={left} x2={width - right} y1={y(max * fraction)} y2={y(max * fraction)} /><text className="stats-graph-y-label" textAnchor="end" x={left - 8} y={y(max * fraction) + 4}>R {Math.round(max * fraction).toLocaleString("en-ZA")}</text></g>)}<path className="stats-graph-area" d={area} /><path className="stats-graph-line" d={line} />{points.map((point, index) => <g key={point.day.toISOString()}><title>{point.day.toLocaleDateString("en-ZA", { day: "numeric", month: "short" })}: R {point.revenue.toFixed(2)} · {point.count} orders</title><circle className="stats-graph-point" cx={x(index)} cy={y(point.revenue)} r="4" />{(index % labelStep === 0 || index === points.length - 1) ? <text className="stats-graph-label" textAnchor="middle" x={x(index)} y={height - 16}>{point.day.toLocaleDateString("en-ZA", { day: "numeric", month: "short" })}</text> : null}</g>)}</svg></div><p className="stats-graph-note">Hover a point to inspect daily paid revenue and order volume.</p></section>;
}

export function AdminDashboardClient() {
  const { products } = useProducts(false); const { orders } = useOrders(); const paid = orders.filter((order) => order.paymentStatus === "paid"); const revenue = paid.reduce((total, order) => total + (order.totalAmount || 0), 0); const lowStock = products.filter((product) => product.inventoryCount <= 5);
  return <><section className="admin-grid"><article><p className="eyebrow">Revenue</p><strong>R {revenue.toFixed(2)}</strong><span>Paid orders</span></article><article><p className="eyebrow">Orders</p><strong>{orders.length}</strong><span>All-time orders</span></article><article><p className="eyebrow">Published</p><strong>{products.filter((product) => product.isPublished).length}</strong><span>Live products</span></article><article><p className="eyebrow">Attention</p><strong>{lowStock.length}</strong><span>Low-stock products</span></article></section><StatsGraph orders={orders} /><section className="admin-dashboard-columns"><section className="admin-panel"><div className="section-heading tight"><div><p className="eyebrow">Latest activity</p><h2>Recent orders</h2></div><Link className="text-link" href="/admin/orders">View all</Link></div>{orders.length ? <div className="admin-activity-list">{orders.slice(0, 5).map((order) => <div key={order.id}><span><strong>#{order.id.slice(0, 8)}</strong><small>{order.customer?.name ?? "Customer"} · {dateLabel(order.createdAt)}</small></span><b>R {(order.totalAmount ?? 0).toFixed(2)}</b><em className={`status status-${order.shippingStatus}`}>{order.shippingStatus}</em></div>)}</div> : <p className="empty-catalog">Orders will appear here as customers check out.</p>}</section><section className="admin-panel"><div className="section-heading tight"><div><p className="eyebrow">Inventory</p><h2>Needs attention</h2></div><Link className="text-link" href="/admin/products">Manage products</Link></div>{lowStock.length ? <div className="admin-activity-list">{lowStock.slice(0, 5).map((product) => <div key={product.id}><span><strong>{product.title}</strong><small>{product.category}</small></span><b>{product.inventoryCount} left</b></div>)}</div> : <p className="empty-catalog">All products have more than five units in stock.</p>}</section></section></>;
}
