"use client";

import { useEffect, useState } from "react";
import { Conversation, ConversationMessage, markConversationRead, sendConversationMessage, subscribeConversationMessages, subscribeConversations } from "@/services/firebase-messages";

export function AdminInboxClient() { const [items, setItems] = useState<Conversation[]>([]); const [selected, setSelected] = useState<Conversation | null>(null); const [messages, setMessages] = useState<ConversationMessage[]>([]); const [text, setText] = useState(""); const [manual, setManual] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => subscribeConversations(setItems), []); useEffect(() => { if (!selected) return; void markConversationRead(selected.id); return subscribeConversationMessages(selected.id, setMessages); }, [selected]);
  async function reply(event: React.FormEvent) { event.preventDefault(); if (!text.trim() || !selected) return; const replyText = text; await sendConversationMessage({ conversationId: selected.id, email: selected.customerEmail, name: selected.customerName, text: replyText, sender: "admin", sentVia: "manual_email" }); await fetch("/api/messages/notify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ to: selected.customerEmail, subject: "Reply from Kroon Luxe", text: replyText, conversationId: selected.id, conversationToken: selected.accessToken }) }); setText(""); setNotice("Reply sent."); }
  async function newMessage(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await sendConversationMessage({ email: String(data.get("email")), name: String(data.get("name")), text: String(data.get("message")), sender: "admin", sentVia: "manual_email" }); setManual(false); setNotice("Message sent."); }
  return <section className="inbox"><div className="inbox-heading"><div><p className="eyebrow">Customer care</p><h1>Inbox</h1></div><button className="button button-dark" onClick={() => setManual(!manual)} type="button">New message</button></div>{manual ? <form className="inbox-manual" onSubmit={newMessage}><input name="name" placeholder="Recipient name" required /><input name="email" type="email" placeholder="Recipient email" required /><textarea name="message" placeholder="Write a message" required /><button className="button button-primary">Send</button></form> : null}<div className="inbox-layout"><div className="conversation-list">{items.length ? items.map((item) => <button className={`conversation-row${selected?.id === item.id ? " active" : ""}`} key={item.id} onClick={() => setSelected(item)} type="button"><strong>{item.customerName}</strong><small>{item.customerEmail}</small><span>{item.lastMessage}</span>{item.unreadByAdmin ? <b>New</b> : null}</button>) : <p className="empty-catalog">No conversations yet.</p>}</div><div className="conversation-thread">{selected ? <><div className="thread-header"><h2>{selected.customerName}</h2><span>{selected.customerEmail}</span></div><div className="thread-messages">{messages.map((message) => <div className={`thread-message ${message.sender}`} key={message.id}>{message.text}</div>)}</div><form className="thread-composer" onSubmit={reply}><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a reply" rows={3} /><button className="button button-dark">Reply</button></form></> : <p className="empty-catalog">Select a conversation to read and reply.</p>}</div></div>{notice ? <p className="form-message">{notice}</p> : null}</section>; }
